#import <Cocoa/Cocoa.h>

@interface EventTap : NSObject {
	CFMachPortRef _ref;
	NSMutableString * _buffer;
}

- (id)initWithCallback:(id)thisObject withSelector:(SEL)thisSelector;
- (void)enable;
- (void)pause;
- (void)resume;
- (void)disable;
- (CGEventRef)keyEventReceived:(CGEventRef)event ;

enum keyCodes {
    keyCodeZero = 29,
    keyCodeOne = 18,
    keyCodeTwo = 19,
    keyCodeThree = 20,
    keyCodeFour = 21,
    keyCodeFive = 23,
    keyCodeSix = 22,
    keyCodeSeven = 26,
    keyCodeEight = 28,
    keyCodeNine = 25,
    keyCodeA = 0,
    keyCodeB = 11,
    keyCodeC = 8,
    keyCodeD = 2,
    keyCodeE = 14,
    keyCodeF = 3,
    keyCodeG = 5,
    keyCodeH = 4,
    keyCodeI = 34,
    keyCodeJ = 38,
    keyCodeK = 40,
    keyCodeL = 37,
    keyCodeM = 46,
    keyCodeN = 45,
    keyCodeO = 31,
    keyCodeP = 35,
    keyCodeQ = 12,
    keyCodeR = 15,
    keyCodeS = 1,
    keyCodeT = 17,
    keyCodeU = 32,
    keyCodeV = 9,
    keyCodeW = 13,
    keyCodeX = 7,
    keyCodeY = 16,
    keyCodeZ = 6,
    keyCodeSectionSign = 10,
    keyCodeGrave = 50,
    keyCodeMinus = 27,
    keyCodeEqual = 24,
    keyCodeLeftBracket = 33,
    keyCodeRightBracket = 30,
    keyCodeSemicolon = 41,
    keyCodeQuote = 39,
    keyCodeComma = 43,
    keyCodePeriod = 47,
    keyCodeSlash = 44,
    keyCodeBackslash = 42,
    keyCodeKeypad0 = 82,
    keyCodeKeypad1 = 83,
    keyCodeKeypad2 = 84,
    keyCodeKeypad3 = 85,
    keyCodeKeypad4 = 86,
    keyCodeKeypad5 = 87,
    keyCodeKeypad6 = 88,
    keyCodeKeypad7 = 89,
    keyCodeKeypad8 = 91,
    keyCodeKeypad9 = 92,
    keyCodeKeypadDecimal = 65,
    keyCodeKeypadMultiply = 67,
    keyCodeKeypadPlus = 69,
    keyCodeKeypadDivide = 75,
    keyCodeKeypadMinus = 78,
    keyCodeKeypadEquals = 81,
    keyCodeKeypadClear = 71,
    keyCodeKeypadEnter = 76,
    keyCodeSpace = 49,
    keyCodeReturn = 36,
    keyCodeTab = 48,
    keyCodeDelete = 51,
    keyCodeForwardDelete = 117,
    keyCodeLinefeed = 52,
    keyCodeEscape = 53,
    keyCodeCommand = 55,
    keyCodeShift = 56,
    keyCodeCapsLock = 57,
    keyCodeOption = 58,
    keyCodeControl = 59,
    keyCodeRightShift = 60,
    keyCodeRightOption = 61,
    keyCodeRightControl = 62,
    keyCodeFunction = 63,
    keyCodeF1 = 122,
    keyCodeF2 = 120,
    keyCodeF3 = 99,
    keyCodeF4 = 118,
    keyCodeF5 = 96,
    keyCodeF6 = 97,
    keyCodeF7 = 98,
    keyCodeF8 = 100,
    keyCodeF9 = 101,
    keyCodeF10 = 109,
    keyCodeF11 = 103,
    keyCodeF12 = 111,
    keyCodeF13 = 105,
    keyCodeF14 = 107,
    keyCodeF15 = 113,
    keyCodeF16 = 106,
    keyCodeF17 = 64,
    keyCodeF18 = 79,
    keyCodeF19 = 80,
    keyCodeF20 = 90,
    keyCodeVolumeUp = 72,
    keyCodeVolumeDown = 73,
    keyCodeMute = 74,
    keyCodeHelpInsert = 114,
    keyCodeHome = 115,
    keyCodeEnd = 119,
    keyCodePageUp = 116,
    keyCodePageDown = 121,
    keyCodeLeftArrow = 123,
    keyCodeRightArrow = 124,
    keyCodeDownArrow = 125,
    keyCodeUpArrow = 126
};

@end
